### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by dme65** [zi-w/Ensemble-Bayesian-Optimization#2]
Hi,

Thank you for sharing your code! Can you make the code compatible with Python3? I'm interested in comparing to EBO, but I need to use Python3.

Cheers,
David

**Comment by gehring** [comment]
@dme65 I'll look into this over the weekend. Unless there are any unexpected difficulties, we should be able to make EBO python 3 compatible.

**Comment by dme65** [comment]
Thank you! I'm looking forward to that :)

**Comment by samfairman** [comment]
Hi,

I am also interested in using your code with Python3. Is there any update with this? 

EDIT: sorry I didn't see your  unmerged py3 branch. I just installed it on MacOS 10.14.6 and it the test_ebo.py worked with no errors. I do not use Linux so I was unsure how to do the apt-get commands so I did not use them. However I imagine I will probably run into problems later. Should I try to install the following? Or are these specific to Linux? 

apt-get -y install build-essential python-dev python-setuptools libatlas-dev libatlas3gf-base
apt-get -y install libsuitesparse-dev

Here are the commands I used to get it to work on MacOS: 

conda create -n EBOpy3
conda activate EBOpy3
curl -fSsL https://bootstrap.pypa.io/get-pip.py | python
pip install -U pip setuptools
pip install -U requests
pip install -U msrest
pip install azure-storage==0.32.0
pip install cython
conda install scipy
conda install scikit-learn
conda install -c conda-forge scikit-sparse
conda install matplotlib

Thanks,
Sam

**Comment by zi-w** [comment]
Hi Sam, Thanks very much for sharing your installation experience on MacOS. What we had in https://github.com/zi-w/Ensemble-Bayesian-Optimization/blob/master/configs/start_commands is specific to Ubuntu 14.04 LTS and Python 2.7, which we used for running experiments on Azure at the time.
